### ISSUE TITLE
When change left position, dragger isn't accurate

### ISSUE THREAD

**Issue by Horray** [tovic/range-slider#2]
If I make the sliders position to absolute (or the sliders wrapper), and change the left amount, and you start dragging the dragger, it goes to the wrong position. Here's a JSFiddle showing what I mean:

https://jsfiddle.net/rxo8ae86/

**Comment by taufik-nurrohman** [comment]
Use `padding-left` &rarr; https://jsfiddle.net/tovic/rxo8ae86/1

I don&rsquo;t have any plan to make this supports the absolute position and such. I will let another developers to do that for us.

**Comment by taufik-nurrohman** [comment]
http://jsbin.com/jugecupawu/edit?html,output fixed :smile:
