### ISSUE TITLE
Multiple Handle(s)

### ISSUE THREAD

**Issue by coding-saints** [tovic/range-slider#5]
is there going to be a way to use multiple handles? I guess this is more of a feature request

**Comment by taufik-nurrohman** [comment]
Depends. What does _multiple handles_ means in your context?

**Comment by taufik-nurrohman** [comment]
Apply to multiple HTML elements at once &rarr; https://github.com/tovic/range-slider/wiki/Apply-to-Multiple-HTML-Elements-at-Once

**Comment by coding-saints** [comment]
My thought was "1" slide(r) with 4 (or more) handles to toggle on that  slide. So if i wanted to have a slider to toggle values 2-4 and 6-8    --|--|----|--|--

Or if I wanted 2 and 4 AND 6 targeted   --|--|--|-- 
I hope that makes sense. I noticed a lot of sliders refer to 'upper' and 'lower' bounds. I want to not be restricted to how many handles a single slider has. 
Thank you for responding by the way.

**Comment by taufik-nurrohman** [comment]
I think I have the idea which is by stacking two or more sliders in a single container. Next time I will push a demo page for this concept.

**Comment by taufik-nurrohman** [comment]
Still hacky, somebody should be able to add this feature easily using some of the internal functions, then append the handle element multiple times based on the length value defined in the configuration, etc. As mentioned in the title, I will keep this plugin in the simplest mode.

**Comment by taufik-nurrohman** [comment]
https://rawgit.com/tovic/range-slider/master/range-slider.multiple-range.html

**Comment by coding-saints** [comment]
Awesome, I will play around with it today. Thank you
